package util;

public enum EventType {
	UNTYPED, SWAP_STUDY, SWAP_CARD_VIEW, SWAP_CARD_CREATE_VIEW,
	STUDY_MODE_PICKED, STUDY_SHOW_ANSWER, STUDY_GOT_ANSWER, FILE_OPEN, 
	FILE_SAVE_AS, FILE_SAVE, FILE_NEW, MODEL_TITLE_CHANGE, FILE_EXIT,
	CARD_ADD_TO_STACK, STACK_TITLE_CHANGE, MODEL_STACK_CHANGE, 
	EDIT_CARD, CLEAR_EDIT, DELETE_CARD, CHECK_UPDATES
}
